### ISSUE TITLE
Update _config.yml file

### ISSUE THREAD

**Issue by lukaszklis** [verpixelt/moby#17]
It looks like some data should be updated in the `_config.yml` file, i.e. description, url, twitter & github. Possibly, Google Analytics ID in case if we want to use it.

**Comment by verpixelt** [comment]
If copied the settings from the current live page into this conifg file (bcedab6ed0f794d8a1facc335d308ea068757855). Is there anything else we **need**?

**Comment by lukaszklis** [comment]
LGTM :+1:
