### ISSUE TITLE
Use meetup's API for a list of the upcoming events

### ISSUE THREAD

**Issue by lukaszklis** [verpixelt/moby#18]
Let's use Jekyll's `_data` to manage the upcoming events in the simplest way as we can. ;)

**Comment by verpixelt** [comment]
The question is, aren't all our CSSclasses meetups posted on meetup.com anyway?! If so we could simply use their API(http://www.meetup.com/meetup_api/) to automatically display new events on our page. /cc @bastianalbers

**Comment by bastianalbers** [comment]
Yeah, we do that on the OTS homepage. We can look into it to see how that works (i didn't code that part)

**Comment by lukaszklis** [comment]
Sounds amazing. Totally forgot about meetup.com's API. ;)

**Comment by verpixelt** [comment]
Cool let's do this. Maybe we've time for it during the event on Sunday. This is nothing crucial for the next workshop.
